services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: Mahfuz
      DB_PASSWORD: Mahfuz@123
      DATABASE_NAME: humans_unite_backend_development
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: humans_unite_backend_development
      MYSQL_USER: Mahfuz
      MYSQL_PASSWORD: Mahfuz@123
      MYSQL_ROOT_PASSWORD: mysql123
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
